### ISSUE TITLE
Many materials don't work

### ISSUE THREAD

**Issue by joex92** [Cnly/WowSuchCleaner#6]
All Netherite items don't work as Materials
```yaml
[19:40:16 ERROR]: Error occurred while enabling WowSuchCleaner v1.9.2 (Is it up to date?)
java.util.NoSuchElementException: Material not found: NETHERITE_HELMET
        at io.github.Cnly.WowSuchCleaner.Crafter.Crafter.utils.ItemUtils.getItemByTypeString(ItemUtils.java:66) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.config.auction.AuctionableItem.fromMap(AuctionableItem.java:50) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.config.auction.AuctionConfig.load(AuctionConfig.java:69) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.config.auction.AuctionConfig.<init>(AuctionConfig.java:24) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.config.SharedConfigManager.load(SharedConfigManager.java:59) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.config.SharedConfigManager.<init>(SharedConfigManager.java:33) ~[WowSuchCleaner-1.9.2.jar:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.Main.onEnable(Main.java:69) ~[WowSuchCleaner-1.9.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1393]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Purpur-1393]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:532) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:494) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1393]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1393]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[19:40:16 INFO]: [WowSuchCleaner] Disabling WowSuchCleaner v1.9.2
```
I get this error with many items... why do they not work?

**Comment by joex92** [comment]
I had to do this:
```yaml
#       - item: NETHERITE_HELMET
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_CHESTPLATE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_LEGGINGS
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_BOOTS
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_SWORD
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_AXE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_PICKAXE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_SHOVEL
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: NETHERITE_HOE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
        - item: DIAMOND_HELMET
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_CHESTPLATE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_LEGGINGS
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_BOOTS
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_SWORD
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_AXE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DIAMOND_PICKAXE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
#       - item: DIAMOND_SHOVEL
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 100000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
        - item: DIAMOND_HOE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 100000.00
          minimumIncrement: 1000.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
#       - item: GOLDEN_HELMET
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_CHESTPLATE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_LEGGINGS
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_BOOTS
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_SWORD
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_AXE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_PICKAXE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_SHOVEL
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
#       - item: GOLDEN_HOE
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 10000.00
#         minimumIncrement: 1000.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
        - item: IRON_HELMET
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_CHESTPLATE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_LEGGINGS
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_BOOTS
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_SWORD
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_AXE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: IRON_PICKAXE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
#       - item: IRON_SHOVEL
#         minDurabilityPercent: 1
#         maxDurabilityPercent: 100
#         startingPrice: 1000.00
#         minimumIncrement: 10.00
#         preserveTimeInSeconds: 600
#         auctionDurationInSeconds: 300
        - item: IRON_HOE
          minDurabilityPercent: 1
          maxDurabilityPercent: 100
          startingPrice: 1000.00
          minimumIncrement: 10.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
        - item: DEFAULT
          minDurabilityPercent: 0
          maxDurabilityPercent: 100
          startingPrice: 100.00
          minimumIncrement: 1.00
          preserveTimeInSeconds: 600
          auctionDurationInSeconds: 300
```
because I get error with every single item commented out here
why shovels are not working? also golden items don't work too...

**Comment by joex92** [comment]
more materials that don't work:
- Trident
- Totem of Undying
- Crossbow
