### ISSUE TITLE
I don't know what the reason was for the error

### ISSUE THREAD

**Issue by yuankun1** [Cnly/WowSuchCleaner#8]
[11:55:25] [Server thread/WARN]: [WowSuchCleaner] Task #81 for WowSuchCleaner v1.9.2 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_333]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_333]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_333]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.listeners.BidHandler.cancelInvalidBidState(BidHandler.java:179) ~[?:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.data.auction.AuctionDataManager.removeLot(AuctionDataManager.java:168) ~[?:?]
        at io.github.Cnly.WowSuchCleaner.WowSuchCleaner.data.auction.AuctionDataManager$LotMaintainTask.run(AuctionDataManager.java:571) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:900) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]

**Comment by yuankun1** [comment]
I was bidding when he showed the error
